---
url: http://localhost:8888/oven/
approot: /Users/brodie/projects/oven2/
structure: /Users/brodie/projects/oven2/config/structure.pages
output_directory: /Applications/MAMP/htdocs/oven/
#cache: cache/
templates: templates/
filters: app/filters
header: shared/header
footer: shared/footer


